name: WatchLogs
author: Boulldogo
main: fr.Boulldogo.WatchLogs.WatchLogsPlugin
version: 1.3.3
api-version: 1.13
soft-depends: [LuckPerms]
description: Advanced logging plugin for minecraft server
commands:
  watchlogs:
    description: Main command of WatchLogs plugin 
    aliases: [wl, watchlogs, watchl, wlogs]